In [1]:
import time
from google.cloud import storage
from google.cloud import bigquery
from google.api_core.exceptions import GoogleAPIError
%load_ext google.cloud.bigquery

# **Consumption Layer**

In [4]:
%%bigquery
select table_name from movie_stg.INFORMATION_SCHEMA.TABLES order by table_name

Query is running:   0%|          |

Downloading:   0%|          |

                table_name
0                    Actor
1                Character
2                     Crew
3                    Genre
4                    Movie
5              Movie_Genre
6            Movie_History
7            Movie_Service
8                   Person
9           Person_History
10                   Snack
11           Snack_Service
12                 Theater
13              Tmdb_Movie
14      Tmdb_Movie_History
15  Tmdb_Movie_History_tmp
16             Tmdb_Person
17     Tmdb_Person_History
18              tmdb_movie

**Actor**

In [27]:
%%bigquery
create or replace table movie_csp.Actor(
  credit_id STRING not null,
  person_id INTEGER not null,
  movie_id INTEGER not null,
  name STRING,
  character STRING,
  gender INTEGER,
  credit_order INTEGER,
  data_source STRING not null,
  load_time TIMESTAMP not null,
  effective_time TIMESTAMP default current_timestamp() not null,
  discontinue_time TIMESTAMP,
  status_flag BOOL not null,
  primary key (credit_id, effective_time) not enforced)
  as select *, current_timestamp, null, true
  from movie_stg.Actor;

Query is running:   0%|          |

Empty DataFrame
Columns: []
Index: []

In [28]:
%%bigquery
select c.column_name, c.data_type, c.is_nullable, c.column_default, k.constraint_name
from movie_csp.INFORMATION_SCHEMA.COLUMNS c left join movie_csp.INFORMATION_SCHEMA.KEY_COLUMN_USAGE k
on c.table_name = k.table_name and c.column_name = k.column_name
where c.table_name = 'Actor'
order by c.ordinal_position;

Query is running:   0%|          |

Downloading:   0%|          |

,column_name,data_type,is_nullable,column_default,constraint_name
0,credit_id,STRING,NO,NULL,Actor.pk$
1,person_id,INT64,NO,NULL,None
2,movie_id,INT64,NO,NULL,None
3,name,STRING,YES,NULL,None
4,character,STRING,YES,NULL,None
5,gender,INT64,YES,NULL,None
6,credit_order,INT64,YES,NULL,None
7,data_source,STRING,NO,NULL,None
8,load_time,TIMESTAMP,NO,NULL,None
9,effective_time,TIMESTAMP,NO,current_timestamp(),Actor.pk$
10,discontinue_time,TIMESTAMP,YES,NULL,None
11,status_flag,BOOL,NO,NULL,None

In [29]:
%%bigquery
select * from movie_csp.Actor
limit 5

Query is running:   0%|          |

Downloading:   0%|          |

,credit_id,person_id,movie_id,name,character,gender,credit_order,data_source,load_time,effective_time,discontinue_time,status_flag
0,6565fcef6f53e100c659e447,128761,1211067,Laura Pizzirani,Rita,0,0,tmdb,2024-02-14 01:27:38.706796+00:00,2024-02-20 04:47:05.561033+00:00,NaT,True
1,64a3b65e8289a000ebe48ee7,3802170,1147701,Luna Depuydt Song,Chenghua,0,0,tmdb,2024-02-14 01:27:38.706796+00:00,2024-02-20 04:47:05.561033+00:00,NaT,True
2,64ec10f1d48cee013a0c09fe,3949972,1166092,Erik Gabrielsen,Sal Vitale,0,0,tmdb,2024-02-14 01:27:38.706796+00:00,2024-02-20 04:47:05.561033+00:00,NaT,True
3,5f1060f96743fa0035d36018,1705254,724901,Vincent Van Horn,Andy,0,0,tmdb,2024-02-14 01:27:38.706796+00:00,2024-02-20 04:47:05.561033+00:00,NaT,True
4,5503692cc3a36862da00003b,1439477,264859,Petra van Hoven,None,0,0,tmdb,2024-02-14 01:27:38.706796+00:00,2024-02-20 04:47:05.561033+00:00,NaT,True

**Character**

In [30]:
%%bigquery
create or replace table movie_csp.Character(
  credit_id	STRING not null,
  person_id INT64 not null,
  movie_id INT64 not null,
  name STRING,
  character STRING,
  credit_order INT64,
  data_source	STRING not null,
  load_time	TIMESTAMP not null,
  effective_time TIMESTAMP default current_timestamp() not null,
  discontinue_time TIMESTAMP,
  status_flag BOOL not null,
  primary key (credit_id, effective_time) not enforced)
  as select *, current_timestamp(), null, true
  from movie_stg.Character;

Query is running:   0%|          |

Empty DataFrame
Columns: []
Index: []

In [31]:
%%bigquery
select c.column_name, c.data_type, c.is_nullable, c.column_default, k.constraint_name
from movie_csp.INFORMATION_SCHEMA.COLUMNS c left join movie_csp.INFORMATION_SCHEMA.KEY_COLUMN_USAGE k
on c.table_name = k.table_name and c.column_name = k.column_name
where c.table_name = 'Character'
order by c.ordinal_position;

Query is running:   0%|          |

Downloading:   0%|          |

,column_name,data_type,is_nullable,column_default,constraint_name
0,credit_id,STRING,NO,NULL,Character.pk$
1,person_id,INT64,NO,NULL,None
2,movie_id,INT64,NO,NULL,None
3,name,STRING,YES,NULL,None
4,character,STRING,YES,NULL,None
5,credit_order,INT64,YES,NULL,None
6,data_source,STRING,NO,NULL,None
7,load_time,TIMESTAMP,NO,NULL,None
8,effective_time,TIMESTAMP,NO,current_timestamp(),Character.pk$
9,discontinue_time,TIMESTAMP,YES,NULL,None
10,status_flag,BOOL,NO,NULL,None

In [32]:
%%bigquery
select * from movie_csp.Character
limit 5

Query is running:   0%|          |

Downloading:   0%|          |

,credit_id,person_id,movie_id,name,character,credit_order,data_source,load_time,effective_time,discontinue_time,status_flag
0,52fe4339c3a36847f8043b9b,8229,2134,Rod Taylor,H. George Wells,0,tmdb,2024-02-14 01:27:08.699919+00:00,2024-02-20 04:48:04.771981+00:00,NaT,True
1,52fe4a1dc3a36847f81ba60d,80602,103370,Tyler Perry,Madea / Joe / Brian,0,tmdb,2024-02-14 01:27:08.699919+00:00,2024-02-20 04:48:04.771981+00:00,NaT,True
2,52fe44b79251416c9101a63d,13784,32068,Burt Lancaster,Joe Bass,0,tmdb,2024-02-14 01:27:08.699919+00:00,2024-02-20 04:48:04.771981+00:00,NaT,True
3,52fe43d19251416c7501f73b,62019,10925,Clu Gulager,Burt Wilson,0,tmdb,2024-02-14 01:27:08.699919+00:00,2024-02-20 04:48:04.771981+00:00,NaT,True
4,61c4d0b1efd3c200608e6e7a,3356551,919355,Ryan Livingstone,Braedyn,0,tmdb,2024-02-14 01:27:08.699919+00:00,2024-02-20 04:48:04.771981+00:00,NaT,True

**Crew**

In [33]:
%%bigquery
create or replace table movie_csp.Crew(
  credit_id	STRING not null,
  person_id INT64 not null,
  movie_id INT64 not null,
  name STRING,
  gender INT64,
  department STRING,
  known_for_department STRING,
  job STRING,
  data_source	STRING not null,
  load_time	TIMESTAMP not null,
  effective_time TIMESTAMP default current_timestamp() not null,
  discontinue_time TIMESTAMP,
  status_flag BOOL not null,
  primary key (credit_id, effective_time) not enforced)
  as select *, current_timestamp(), null, true
  from movie_stg.Crew;

Query is running:   0%|          |

Empty DataFrame
Columns: []
Index: []

In [34]:
%%bigquery
select c.column_name, c.data_type, c.is_nullable, c.column_default, k.constraint_name
from movie_csp.INFORMATION_SCHEMA.COLUMNS c left join movie_csp.INFORMATION_SCHEMA.KEY_COLUMN_USAGE k
on c.table_name = k.table_name and c.column_name = k.column_name
where c.table_name = 'Crew'
order by c.ordinal_position;

Query is running:   0%|          |

Downloading:   0%|          |

,column_name,data_type,is_nullable,column_default,constraint_name
0,credit_id,STRING,NO,NULL,Crew.pk$
1,person_id,INT64,NO,NULL,None
2,movie_id,INT64,NO,NULL,None
3,name,STRING,YES,NULL,None
4,gender,INT64,YES,NULL,None
5,department,STRING,YES,NULL,None
6,known_for_department,STRING,YES,NULL,None
7,job,STRING,YES,NULL,None
8,data_source,STRING,NO,NULL,None
9,load_time,TIMESTAMP,NO,NULL,None
10,effective_time,TIMESTAMP,NO,current_timestamp(),Crew.pk$
11,discontinue_time,TIMESTAMP,YES,NULL,None
12,status_flag,BOOL,NO,NULL,None

In [36]:
%%bigquery
select * from movie_csp.Crew
limit 5

Query is running:   0%|          |

Downloading:   0%|          |

,credit_id,person_id,movie_id,name,gender,department,known_for_department,job,data_source,load_time,effective_time,discontinue_time,status_flag
0,6015c0357f05400040c79d30,2958492,393624,Marcia Mitchell,0,Writing,Writing,Book,tmdb,2024-02-14 01:27:22.319767+00:00,2024-02-20 04:48:37.796718+00:00,NaT,True
1,5f24e85b168ea30036b59d82,1172246,162903,Luke Harding,0,Writing,Writing,Book,tmdb,2024-02-14 01:27:22.319767+00:00,2024-02-20 04:48:37.796718+00:00,NaT,True
2,65443f18fd4f8000e47e4407,4354338,10400,Terry Swinton,0,Writing,Writing,Book,tmdb,2024-02-14 01:27:22.319767+00:00,2024-02-20 04:48:37.796718+00:00,NaT,True
3,5b3b3460925141676d01ada8,1466529,339984,Christy Beam,0,Writing,Writing,Book,tmdb,2024-02-14 01:27:22.319767+00:00,2024-02-20 04:48:37.796718+00:00,NaT,True
4,5b0fbca69251415ec800494f,109365,10184,Greg Behrendt,0,Writing,Acting,Book,tmdb,2024-02-14 01:27:22.319767+00:00,2024-02-20 04:48:37.796718+00:00,NaT,True

**Genre**

In [37]:
%%bigquery
create or replace table movie_csp.Genre(
  genre_id INT64 not null,
  name STRING,
  data_source	STRING not null,
  load_time	TIMESTAMP not null,
  effective_time TIMESTAMP default current_timestamp() not null,
  discontinue_time TIMESTAMP,
  status_flag BOOL not null,
  primary key (genre_id, effective_time) not enforced)
  as select *, current_timestamp(), null, true
  from movie_stg.Genre;

Query is running:   0%|          |

Empty DataFrame
Columns: []
Index: []

In [38]:
%%bigquery
select c.column_name, c.data_type, c.is_nullable, c.column_default, k.constraint_name
from movie_csp.INFORMATION_SCHEMA.COLUMNS c left join movie_csp.INFORMATION_SCHEMA.KEY_COLUMN_USAGE k
on c.table_name = k.table_name and c.column_name = k.column_name
where c.table_name = 'Genre'
order by c.ordinal_position;

Query is running:   0%|          |

Downloading:   0%|          |

,column_name,data_type,is_nullable,column_default,constraint_name
0,genre_id,INT64,NO,NULL,Genre.pk$
1,name,STRING,YES,NULL,None
2,data_source,STRING,NO,NULL,None
3,load_time,TIMESTAMP,NO,NULL,None
4,effective_time,TIMESTAMP,NO,current_timestamp(),Genre.pk$
5,discontinue_time,TIMESTAMP,YES,NULL,None
6,status_flag,BOOL,NO,NULL,None

In [40]:
%%bigquery
select * from movie_csp.Genre
limit 5

Query is running:   0%|          |

Downloading:   0%|          |

,genre_id,name,data_source,load_time,effective_time,discontinue_time,status_flag
0,14,Fantasy,tmdb,2024-02-07 03:41:19.340497+00:00,2024-02-20 04:49:42.741650+00:00,NaT,True
1,28,Action,tmdb,2024-02-07 03:41:19.340497+00:00,2024-02-20 04:49:42.741650+00:00,NaT,True
2,9648,Mystery,tmdb,2024-02-07 03:41:19.340497+00:00,2024-02-20 04:49:42.741650+00:00,NaT,True
3,36,History,tmdb,2024-02-07 03:41:19.340497+00:00,2024-02-20 04:49:42.741650+00:00,NaT,True
4,10752,War,tmdb,2024-02-07 03:41:19.340497+00:00,2024-02-20 04:49:42.741650+00:00,NaT,True

**Movie**

In [41]:
%%bigquery
create or replace table movie_csp.Movie(
  tmdb_id INT64 not null,
  imdb_id STRING,
  title STRING,
  original_language STRING,
  overview STRING,
  release_date DATE,
  genre_ids STRING,
  duration INT64,
  directors STRING,
  writers STRING,
  data_source	STRING not null,
  load_time	TIMESTAMP not null,
  effective_time TIMESTAMP default current_timestamp() not null,
  discontinue_time TIMESTAMP,
  status_flag BOOL not null,
  primary key (tmdb_id, effective_time) not enforced)
  as select *, current_timestamp(), null, true
  from movie_stg.Movie;

Query is running:   0%|          |

Empty DataFrame
Columns: []
Index: []

In [37]:
%%bigquery
select c.column_name, c.data_type, c.is_nullable, c.column_default, k.constraint_name
from movie_csp.INFORMATION_SCHEMA.COLUMNS c left join movie_csp.INFORMATION_SCHEMA.KEY_COLUMN_USAGE k
on c.table_name = k.table_name and c.column_name = k.column_name
where c.table_name = 'Movie'
order by c.ordinal_position;

Query is running:   0%|          |

Downloading:   0%|          |

,column_name,data_type,is_nullable,column_default,constraint_name
0,tmdb_id,INT64,NO,NULL,Movie.pk$
1,imdb_id,STRING,YES,NULL,None
2,title,STRING,YES,NULL,None
3,original_language,STRING,YES,NULL,None
4,overview,STRING,YES,NULL,None
5,release_date,DATE,YES,NULL,None
6,genre_ids,STRING,YES,NULL,None
7,duration,INT64,YES,NULL,None
8,directors,STRING,YES,NULL,None
9,writers,STRING,YES,NULL,None
10,data_source,STRING,NO,NULL,None
11,load_time,TIMESTAMP,NO,NULL,None
12,effective_time,TIMESTAMP,NO,current_timestamp(),Movie.pk$
13,discontinue_time,TIMESTAMP,YES,NULL,None
14,status_flag,BOOL,NO,NULL,None

In [44]:
%%bigquery
select * from movie_csp.Movie
limit 5

Query is running:   0%|          |

Downloading:   0%|          |

,tmdb_id,imdb_id,title,original_language,overview,release_date,genre_ids,duration,directors,writers,data_source,load_time,effective_time,discontinue_time,status_flag
0,559974,None,Shock Wave 2,cn,After suffering life changing injuries in the ...,2020-12-24,"[28, 80]",<NA>,None,None,tmdb,2024-02-08 23:34:20.679895+00:00,2024-02-20 04:50:43.845961+00:00,NaT,True
1,664341,None,Eileen,en,"During a bitter 1964 Massachusetts winter, you...",2023-12-01,"[18, 53, 9648, 80]",<NA>,None,None,tmdb,2024-02-08 23:34:20.679895+00:00,2024-02-20 04:50:43.845961+00:00,NaT,True
2,458576,None,Monster Hunter,en,A portal transports Cpt. Artemis and an elite ...,2020-12-03,"[28, 14, 12]",<NA>,None,None,tmdb,2024-02-08 23:34:20.679895+00:00,2024-02-20 04:50:43.845961+00:00,NaT,True
3,228150,None,Fury,en,"In the last months of World War II, as the All...",2014-10-15,"[10752, 18, 28]",<NA>,None,None,tmdb,2024-02-08 23:34:20.679895+00:00,2024-02-20 04:50:43.845961+00:00,NaT,True
4,530382,None,In the Shadow of the Moon,en,"In 1988, Philadelphia police officer Thomas ""L...",2019-09-27,"[878, 53]",<NA>,None,None,tmdb,2024-02-08 23:34:20.679895+00:00,2024-02-20 04:50:43.845961+00:00,NaT,True

**Movie_Genre**

In [5]:
%%bigquery
create or replace table movie_csp.Movie_Genre (
  movie_genre_id STRING not null,
  movie_id INT64 not null,
  genre_id INT64 not null,
  data_source STRING not null,
  load_time TIMESTAMP not null,
  effective_time TIMESTAMP default current_timestamp() not null,
  discontinue_time TIMESTAMP,
  status_flag BOOL not null,
  primary key (movie_genre_id, effective_time) not enforced)
  as select *, current_timestamp(), null, true
  from movie_stg.Movie_Genre;

Query is running:   0%|          |

Empty DataFrame
Columns: []
Index: []

In [61]:
%%bigquery
select c.column_name, c.data_type, c.is_nullable, c.column_default, k.constraint_name
from movie_csp.INFORMATION_SCHEMA.COLUMNS c left join movie_csp.INFORMATION_SCHEMA.KEY_COLUMN_USAGE k
on c.table_name = k.table_name and c.column_name = k.column_name
where c.table_name = 'Movie_Genre'
order by c.ordinal_position;

Query is running:   0%|          |

Downloading:   0%|          |

,column_name,data_type,is_nullable,column_default,constraint_name
0,movie_genre_id,STRING,NO,NULL,Movie_Genre.pk$
1,movie_id,INT64,NO,NULL,None
2,genre_id,INT64,NO,NULL,None
3,data_source,STRING,NO,NULL,None
4,load_time,TIMESTAMP,NO,NULL,None
5,effective_time,TIMESTAMP,NO,current_timestamp(),Movie_Genre.pk$
6,discontinue_time,TIMESTAMP,YES,NULL,None
7,status_flag,BOOL,NO,NULL,None

In [50]:
%%bigquery
select * from movie_csp.Movie_Genre
limit 5

Query is running:   0%|          |

Downloading:   0%|          |

,movie_genre_id,movie_id,genre_id,data_source,load_time,effective_time,discontinue_time,status_flag
0,753342-10752,753342,10752,tmdb,2024-02-07 03:41:55.938198+00:00,2024-02-20 04:54:06.325558+00:00,NaT,True
1,918692-10752,918692,10752,tmdb,2024-02-07 03:41:55.938198+00:00,2024-02-20 04:54:06.325558+00:00,NaT,True
2,508883-12,508883,12,tmdb,2024-02-07 03:41:55.938198+00:00,2024-02-20 04:54:06.325558+00:00,NaT,True
3,940551-12,940551,12,tmdb,2024-02-07 03:41:55.938198+00:00,2024-02-20 04:54:06.325558+00:00,NaT,True
4,1022796-12,1022796,12,tmdb,2024-02-07 03:41:55.938198+00:00,2024-02-20 04:54:06.325558+00:00,NaT,True

**Movie_History**

In [7]:
%%bigquery
create or replace table movie_csp.Movie_History (
  record_date DATE not null,
  movie_id INT64 not null,
  popularity FLOAT64,
  vote_average FLOAT64,
  vote_count INT64,
  data_source STRING not null,
  load_time TIMESTAMP not null,
  effective_time TIMESTAMP default current_timestamp() not null,
  discontinue_time TIMESTAMP,
  status_flag BOOL not null,
  primary key (record_date, movie_id, effective_time) not enforced)
  as select *, current_timestamp(), null, true
  from movie_stg.Movie_History;

Query is running:   0%|          |

Empty DataFrame
Columns: []
Index: []

In [8]:
%%bigquery
select c.column_name, c.data_type, c.is_nullable, c.column_default, k.constraint_name
from movie_csp.INFORMATION_SCHEMA.COLUMNS c left join movie_csp.INFORMATION_SCHEMA.KEY_COLUMN_USAGE k
on c.table_name = k.table_name and c.column_name = k.column_name
where c.table_name = 'Movie_History'
order by c.ordinal_position;

Query is running:   0%|          |

Downloading:   0%|          |

,column_name,data_type,is_nullable,column_default,constraint_name
0,record_date,DATE,NO,NULL,Movie_History.pk$
1,movie_id,INT64,NO,NULL,Movie_History.pk$
2,popularity,FLOAT64,YES,NULL,None
3,vote_average,FLOAT64,YES,NULL,None
4,vote_count,INT64,YES,NULL,None
5,data_source,STRING,NO,NULL,None
6,load_time,TIMESTAMP,NO,NULL,None
7,effective_time,TIMESTAMP,NO,current_timestamp(),Movie_History.pk$
8,discontinue_time,TIMESTAMP,YES,NULL,None
9,status_flag,BOOL,NO,NULL,None

In [59]:
%%bigquery
select * from movie_csp.Movie_History
limit 5

Query is running:   0%|          |

Downloading:   0%|          |

,movie_id,popularity,vote_average,vote_count,data_source,load_time,effective_time,discontinue_time,status_flag
0,185698,18.065,2.0,2,tmdb,2024-02-08 23:34:20.679895+00:00,2024-02-20 04:56:46.430575+00:00,NaT,True
1,879672,20.709,2.0,2,tmdb,2024-02-08 23:34:20.679895+00:00,2024-02-20 04:56:46.430575+00:00,NaT,True
2,369196,15.767,3.0,103,tmdb,2024-02-08 23:34:20.679895+00:00,2024-02-20 04:56:46.430575+00:00,NaT,True
3,1127209,23.422,3.0,2,tmdb,2024-02-08 23:34:20.679895+00:00,2024-02-20 04:56:46.430575+00:00,NaT,True
4,657654,25.283,3.0,2,tmdb,2024-02-08 23:34:20.679895+00:00,2024-02-20 04:56:46.430575+00:00,NaT,True

**Movie_Service**

In [62]:
%%bigquery
create or replace table movie_csp.Movie_Service (
  service_id STRING not null,
  movie_id INT64 not null,
  service_type STRING,
  theater_id INT64,
  data_source STRING not null,
  load_time TIMESTAMP not null,
  effective_time TIMESTAMP default current_timestamp() not null,
  discontinue_time TIMESTAMP,
  status_flag BOOL not null,
  primary key (service_id, effective_time) not enforced)
  as select *, current_timestamp(), null, true
  from movie_stg.Movie_Service;

Query is running:   0%|          |

Empty DataFrame
Columns: []
Index: []

In [64]:
%%bigquery
select c.column_name, c.data_type, c.is_nullable, c.column_default, k.constraint_name
from movie_csp.INFORMATION_SCHEMA.COLUMNS c left join movie_csp.INFORMATION_SCHEMA.KEY_COLUMN_USAGE k
on c.table_name = k.table_name and c.column_name = k.column_name
where c.table_name = 'Movie_Service'
order by c.ordinal_position;

Query is running:   0%|          |

Downloading:   0%|          |

,column_name,data_type,is_nullable,column_default,constraint_name
0,service_id,STRING,NO,NULL,Movie_Service.pk$
1,movie_id,INT64,NO,NULL,None
2,service_type,STRING,YES,NULL,None
3,theater_id,INT64,YES,NULL,None
4,data_source,STRING,NO,NULL,None
5,load_time,TIMESTAMP,NO,NULL,None
6,effective_time,TIMESTAMP,NO,current_timestamp(),Movie_Service.pk$
7,discontinue_time,TIMESTAMP,YES,NULL,None
8,status_flag,BOOL,NO,NULL,None

In [65]:
%%bigquery
select * from movie_csp.Movie_Service
limit 5

Query is running:   0%|          |

Downloading:   0%|          |

,service_id,movie_id,service_type,theater_id,data_source,load_time,effective_time,discontinue_time,status_flag
0,cf567910-f64e,1145857,in-theaters,3343,tmdb_github,2024-02-16 00:36:35.979100+00:00,2024-02-20 04:59:12.099223+00:00,NaT,True
1,c20689dc-de97,1145857,in-theaters,3632,tmdb_github,2024-02-16 00:36:35.979100+00:00,2024-02-20 04:59:12.099223+00:00,NaT,True
2,5401f6dd-eea4,1145857,in-theaters,5927,tmdb_github,2024-02-16 00:36:35.979100+00:00,2024-02-20 04:59:12.099223+00:00,NaT,True
3,3eb6fbdd-a340,1228545,in-theaters,1667,tmdb_github,2024-02-16 00:36:35.979100+00:00,2024-02-20 04:59:12.099223+00:00,NaT,True
4,10a9f3f4-8d54,1228545,in-theaters,4483,tmdb_github,2024-02-16 00:36:35.979100+00:00,2024-02-20 04:59:12.099223+00:00,NaT,True

**Person**

In [2]:
%%bigquery
create or replace table movie_csp.Person (
  person_id INT64 not null,
  name STRING not null,
  also_known_as STRING,
  biography STRING,
  birth_day INT64,
  birth_month INT64,
  birth_year INT64,
  death_day INT64,
  death_month INT64,
  death_year INT64,
  gender INT64,
  homepage STRING,
  place_of_birth STRING,
  imdb_id STRING,
  known_for_department STRING,
  popularity FLOAT64,
  data_source STRING not null,
  load_time TIMESTAMP not null,
  effective_time TIMESTAMP default current_timestamp() not null,
  discontinue_time TIMESTAMP,
  status_flag BOOL not null,
  primary key (person_id, effective_time) not enforced)
  as select *, current_timestamp(), null, true
  from movie_stg.Person;

Query is running:   0%|          |

Empty DataFrame
Columns: []
Index: []

In [3]:
%%bigquery
select c.column_name, c.data_type, c.is_nullable, c.column_default, k.constraint_name
from movie_csp.INFORMATION_SCHEMA.COLUMNS c left join movie_csp.INFORMATION_SCHEMA.KEY_COLUMN_USAGE k
on c.table_name = k.table_name and c.column_name = k.column_name
where c.table_name = 'Person'
order by c.ordinal_position;

Query is running:   0%|          |

Downloading:   0%|          |

,column_name,data_type,is_nullable,column_default,constraint_name
0,person_id,INT64,NO,NULL,Person.pk$
1,name,STRING,NO,NULL,None
2,also_known_as,STRING,YES,NULL,None
3,biography,STRING,YES,NULL,None
4,birth_day,INT64,YES,NULL,None
5,birth_month,INT64,YES,NULL,None
6,birth_year,INT64,YES,NULL,None
7,death_day,INT64,YES,NULL,None
8,death_month,INT64,YES,NULL,None
9,death_year,INT64,YES,NULL,None
10,gender,INT64,YES,NULL,None
11,homepage,STRING,YES,NULL,None
12,place_of_birth,STRING,YES,NULL,None
13,imdb_id,STRING,YES,NULL,None
14,known_for_department,STRING,YES,NULL,None
15,popularity,FLOAT64,YES,NULL,None
16,data_source,STRING,NO,NULL,None
17,load_time,TIMESTAMP,NO,NULL,None
18,effective_time,TIMESTAMP,NO,current_timestamp(),Person.pk$
19,discontinue_time,TIMESTAMP,YES,NULL,None
20,status_flag,BOOL,NO,NULL,None

In [4]:
%%bigquery
select * from movie_csp.Person
limit 5

Query is running:   0%|          |

Downloading:   0%|          |

,person_id,name,also_known_as,biography,birth_day,birth_month,birth_year,death_day,death_month,death_year,...,homepage,place_of_birth,imdb_id,known_for_department,popularity,data_source,load_time,effective_time,discontinue_time,status_flag
0,1450974,Kyle McQueen,[],None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,None,None,nm6782165,Art,8.375,tmdb,2024-01-31 00:14:21.495095+00:00,2024-03-01 21:36:58.427422+00:00,NaT,True
1,2011980,Claudia Gallardo,[],None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,None,None,None,Art,2.726,tmdb,2024-01-31 00:14:21.495095+00:00,2024-03-01 21:36:58.427422+00:00,NaT,True
2,1458692,Alison Froling,[],None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,None,None,None,Art,3.851,tmdb,2024-01-31 00:14:21.495095+00:00,2024-03-01 21:36:58.427422+00:00,NaT,True
3,2000696,Eric Dilucente,[],None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,None,None,None,Art,2.327,tmdb,2024-01-31 00:14:21.495095+00:00,2024-03-01 21:36:58.427422+00:00,NaT,True
4,3726001,Demetrice Wilson,"[""Demetrice 'D' Wilson ""]",None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,None,None,nm9239822,Art,0.988,tmdb,2024-01-31 00:14:21.495095+00:00,2024-03-01 21:36:58.427422+00:00,NaT,True

**Snack**

In [73]:
%%bigquery
create or replace table movie_csp.Snack (
  id INT64 not null,
  name STRING,
  calories FLOAT64,
  calories_from_fat FLOAT64,
  total_fat FLOAT64,
  saturated_fat FLOAT64,
  trans_fat FLOAT64,
  polyunsat_fat FLOAT64,
  monounsat_fat FLOAT64,
  cholesterol FLOAT64,
  sodium FLOAT64,
  potassium FLOAT64,
  carbohydrates FLOAT64,
  dietary_fiber FLOAT64,
  sugars FLOAT64,
  protein FLOAT64,
  data_source STRING not null,
  load_time TIMESTAMP not null,
  effective_time TIMESTAMP default current_timestamp() not null,
  discontinue_time TIMESTAMP,
  status_flag BOOL not null,
  primary key (id, effective_time) not enforced)
  as select *, current_timestamp(), null, true
  from movie_stg.Snack;

Query is running:   0%|          |

Empty DataFrame
Columns: []
Index: []

In [74]:
%%bigquery
select c.column_name, c.data_type, c.is_nullable, c.column_default, k.constraint_name
from movie_csp.INFORMATION_SCHEMA.COLUMNS c left join movie_csp.INFORMATION_SCHEMA.KEY_COLUMN_USAGE k
on c.table_name = k.table_name and c.column_name = k.column_name
where c.table_name = 'Snack'
order by c.ordinal_position;

Query is running:   0%|          |

Downloading:   0%|          |

,column_name,data_type,is_nullable,column_default,constraint_name
0,id,INT64,NO,NULL,Snack.pk$
1,name,STRING,YES,NULL,None
2,calories,FLOAT64,YES,NULL,None
3,calories_from_fat,FLOAT64,YES,NULL,None
4,total_fat,FLOAT64,YES,NULL,None
5,saturated_fat,FLOAT64,YES,NULL,None
6,trans_fat,FLOAT64,YES,NULL,None
7,polyunsat_fat,FLOAT64,YES,NULL,None
8,monounsat_fat,FLOAT64,YES,NULL,None
9,cholesterol,FLOAT64,YES,NULL,None
10,sodium,FLOAT64,YES,NULL,None
11,potassium,FLOAT64,YES,NULL,None
12,carbohydrates,FLOAT64,YES,NULL,None
13,dietary_fiber,FLOAT64,YES,NULL,None
14,sugars,FLOAT64,YES,NULL,None
15,protein,FLOAT64,YES,NULL,None
16,data_source,STRING,NO,NULL,None
17,load_time,TIMESTAMP,NO,NULL,None
18,effective_time,TIMESTAMP,NO,current_timestamp(),Snack.pk$
19,discontinue_time,TIMESTAMP,YES,NULL,None
20,status_flag,BOOL,NO,NULL,None

In [75]:
%%bigquery
select * from movie_csp.Snack
limit 5

Query is running:   0%|          |

Downloading:   0%|          |

,id,name,calories,calories_from_fat,total_fat,saturated_fat,trans_fat,polyunsat_fat,monounsat_fat,cholesterol,...,potassium,carbohydrates,dietary_fiber,sugars,protein,data_source,load_time,effective_time,discontinue_time,status_flag
0,78,Banana Smoothie 16 fl oz,260.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,70.0,NaN,66.0,NaN,amc,2024-02-07 03:53:10.283111+00:00,2024-02-20 05:08:39.286737+00:00,NaT,True
1,73,Pretzel Bites: Add Icing Cup,230.0,50.0,6.0,3.0,NaN,NaN,NaN,NaN,...,NaN,43.0,NaN,40.0,NaN,amc,2024-02-07 03:53:10.283111+00:00,2024-02-20 05:08:39.286737+00:00,NaT,True
2,81,Mango Smoothie 16 fl oz,270.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,72.0,NaN,68.0,NaN,amc,2024-02-07 03:53:10.283111+00:00,2024-02-20 05:08:39.286737+00:00,NaT,True
3,86,Strawberry Banana Smoothie 16 fl oz,260.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,68.0,NaN,62.0,NaN,amc,2024-02-07 03:53:10.283111+00:00,2024-02-20 05:08:39.286737+00:00,NaT,True
4,84,Peach Smoothie 24 fl oz,390.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,104.0,NaN,101.0,NaN,amc,2024-02-07 03:53:10.283111+00:00,2024-02-20 05:08:39.286737+00:00,NaT,True

**Snack_Service**

In [77]:
%%bigquery
create or replace table movie_csp.Snack_Service (
  theater_name STRING not null,
  snack_id INT64 not null,
  theater_id INT64 not null,
  theater_chain_name STRING not null,
  service_category STRING,
  data_source STRING not null,
  load_time TIMESTAMP not null,
  effective_time TIMESTAMP default current_timestamp() not null,
  discontinue_time TIMESTAMP,
  status_flag BOOL not null,
  primary key (snack_id, theater_id, effective_time) not enforced)
  as select *, current_timestamp(), null, true
  from movie_stg.Snack_Service;

Query is running:   0%|          |

Empty DataFrame
Columns: []
Index: []

In [78]:
%%bigquery
select c.column_name, c.data_type, c.is_nullable, c.column_default, k.constraint_name
from movie_csp.INFORMATION_SCHEMA.COLUMNS c left join movie_csp.INFORMATION_SCHEMA.KEY_COLUMN_USAGE k
on c.table_name = k.table_name and c.column_name = k.column_name
where c.table_name = 'Snack_Service'
order by c.ordinal_position;

Query is running:   0%|          |

Downloading:   0%|          |

,column_name,data_type,is_nullable,column_default,constraint_name
0,theater_name,STRING,NO,NULL,None
1,snack_id,INT64,NO,NULL,Snack_Service.pk$
2,theater_id,INT64,NO,NULL,Snack_Service.pk$
3,theater_chain_name,STRING,NO,NULL,None
4,service_category,STRING,YES,NULL,None
5,data_source,STRING,NO,NULL,None
6,load_time,TIMESTAMP,NO,NULL,None
7,effective_time,TIMESTAMP,NO,current_timestamp(),Snack_Service.pk$
8,discontinue_time,TIMESTAMP,YES,NULL,None
9,status_flag,BOOL,NO,NULL,None

In [79]:
%%bigquery
select * from movie_csp.Snack_Service
limit 5

Query is running:   0%|          |

Downloading:   0%|          |

,theater_name,snack_id,theater_id,theater_chain_name,service_category,data_source,load_time,effective_time,discontinue_time,status_flag
0,Cameo Theatres 1 & 2,0,454,South Shore Cinemas,None,amc_github,2024-02-15 22:19:57.087795+00:00,2024-02-20 05:11:04.542698+00:00,NaT,True
1,Mill Wharf Cinema,0,3851,South Shore Cinemas,None,amc_github,2024-02-15 22:19:57.087795+00:00,2024-02-20 05:11:04.542698+00:00,NaT,True
2,East Bridgewater Cinema 6,0,471,South Shore Cinemas,None,amc_github,2024-02-15 22:19:57.087795+00:00,2024-02-20 05:11:04.542698+00:00,NaT,True
3,Plaza 3 Cinema,1,6109,Eisentraut Theatres,None,amc_github,2024-02-15 22:19:57.087795+00:00,2024-02-20 05:11:04.542698+00:00,NaT,True
4,Fox Theatre,1,6115,Eisentraut Theatres,None,amc_github,2024-02-15 22:19:57.087795+00:00,2024-02-20 05:11:04.542698+00:00,NaT,True

**Theater**

In [80]:
%%bigquery
create or replace table movie_csp.Theater (
  id INT64 not null,
  name STRING not null,
  address STRING not null,
  city STRING not null,
  state STRING not null,
  zip INT64 not null,
  country STRING not null,
  theaterChainName STRING not null,
  longitude STRING not null,
  latitude STRING not null,
  data_source STRING not null,
  load_time TIMESTAMP not null,
  effective_time TIMESTAMP default current_timestamp() not null,
  discontinue_time TIMESTAMP,
  status_flag BOOL not null,
  primary key (id, effective_time) not enforced)
  as select *, current_timestamp(), null, true
  from movie_stg.Theater;

Query is running:   0%|          |

Empty DataFrame
Columns: []
Index: []

In [81]:
%%bigquery
select c.column_name, c.data_type, c.is_nullable, c.column_default, k.constraint_name
from movie_csp.INFORMATION_SCHEMA.COLUMNS c left join movie_csp.INFORMATION_SCHEMA.KEY_COLUMN_USAGE k
on c.table_name = k.table_name and c.column_name = k.column_name
where c.table_name = 'Theater'
order by c.ordinal_position;

Query is running:   0%|          |

Downloading:   0%|          |

,column_name,data_type,is_nullable,column_default,constraint_name
0,id,INT64,NO,NULL,Theater.pk$
1,name,STRING,NO,NULL,None
2,address,STRING,NO,NULL,None
3,city,STRING,NO,NULL,None
4,state,STRING,NO,NULL,None
5,zip,INT64,NO,NULL,None
6,country,STRING,NO,NULL,None
7,theaterChainName,STRING,NO,NULL,None
8,longitude,STRING,NO,NULL,None
9,latitude,STRING,NO,NULL,None
10,data_source,STRING,NO,NULL,None
11,load_time,TIMESTAMP,NO,NULL,None
12,effective_time,TIMESTAMP,NO,current_timestamp(),Theater.pk$
13,discontinue_time,TIMESTAMP,YES,NULL,None
14,status_flag,BOOL,NO,NULL,None

In [82]:
%%bigquery
select * from movie_csp.Theater
limit 5

Query is running:   0%|          |

Downloading:   0%|          |

,id,name,address,city,state,zip,country,theaterChainName,longitude,latitude,data_source,load_time,effective_time,discontinue_time,status_flag
0,2907,Simsbury,530 Bushy Hill Road,Simsbury,CT,6070,USA,Hoyts,-72.863399,41.819424,github,2024-01-31 00:28:40.136547+00:00,2024-02-20 05:13:36.749598+00:00,NaT,True
1,872,West Nursery,1591 W. Nursery Road,Linthicum,MD,21090,USA,Hoyts,-76.677665,39.205236,github,2024-01-31 00:28:40.136547+00:00,2024-02-20 05:13:36.749598+00:00,NaT,True
2,312,FunAsia Cinema,1210 E. Belt Line Rd.,Richardson,TX,75081,USA,FunAsiA,-96.7037,32.9452,github,2024-01-31 00:28:40.136547+00:00,2024-02-20 05:13:36.749598+00:00,NaT,True
3,4441,Monaco Pictures,"370 The Bridge Street, NW",Huntsville,AL,35806,USA,Cinemark,-86.67353,34.718965,github,2024-01-31 00:28:40.136547+00:00,2024-02-20 05:13:36.749598+00:00,NaT,True
4,4976,Cinemark Conway Towne Centre,201 Skyline Drive,Conway,AR,72032,USA,Cinemark,-92.430747,35.109712,github,2024-01-31 00:28:40.136547+00:00,2024-02-20 05:13:36.749598+00:00,NaT,True